# Generated by Django 4.2.5 on 2023-09-29 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_advertisements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisements",
            name="image",
            field=models.ImageField(
                default=" ", upload_to="advertisements/", verbose_name="Изображение"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advertisements",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
    ]
