# Generated by Django 4.2.5 on 2023-09-29 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_advertisements", "0002_advertisements_image_advertisements_user"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="advertisements",
            table="advertisements",
        ),
    ]
